module.exports = [{
	test: /\.json5?$/,
	loader: 'json5-loader'
}, {
	test: /\.jsx?$/,
	exclude: /(node_modules|bower_components|build\/)/,
	loaders: ['babel-loader', 'eslint-loader']
}, {
	test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'file-loader'
}, {
	test: /\.(woff|woff2)$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?prefix=font/&limit=5000'
}, {
	test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=application/octet-stream'
}, {
	test: /\.htc$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=application/octet-stream'
}, {
	test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=image/svg+xml'
}, {
	test: /\.gif/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=image/gif'
}, {
	test: /\.jpg/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=image/jpg'
}, {
	test: /\.png/,
	exclude: /(node_modules|bower_components)/,
	loader: 'url-loader?limit=10000&mimetype=image/png'
}];
